### ISSUE TITLE
not working in FF newest version

### ISSUE THREAD

**Issue by nataschaberg** [nkbt/react-copy-to-clipboard#70] opened 2017-07-26 15:46 UTC
Hi, I use FF Version 54.0.1 where copy does not work for me (no error; just nothing happens). In chrome it works perfectly. Is there an issue when using firefox in general or should it work? Thanks for a short feedback!

**Comment by nkbt** [comment] 2017-07-27 22:11
It definitely should work in Firefox, but I could imaging in the new version FF changed something again... I've opened issue in the upstream library, look at https://github.com/sudodoki/copy-to-clipboard/issues/53 for updates

**Comment by nkbt** [comment] 2017-08-13 13:08
@nataschaberg we could not reproduce the issue =(. Maybe you have more details (or it is fixed in later version)?

**Closed** 2017-09-30 12:30 UTC
