### ISSUE TITLE
Chrome Version 73.0.3683.103 prepends a characters of whitespace 

### ISSUE THREAD

**Issue by jonjburgess** [nkbt/react-copy-to-clipboard#107] opened 2019-04-15 09:52 UTC
From Chrome Version 73.0.3683.103 when using the copy function, the browser now adds a single character of whitespace before the copied text

**Comment by nkbt** [comment] 2019-04-15 23:30
Please check your code instead as I cannot reproduce it. Just checked in this exact version of Chrome under Windows.
Please re-open if you have more details

**Closed by nkbt** 2019-04-15 23:30 UTC

**Comment by jonjburgess** [comment] 2019-04-16 14:39
Sorry, should have stated this is on Mac OS 10.13.6. We are in a development team and one of us had the issue but others didn't have the issue.
I tested on my machine with Chrome 72 (didn't make a note of specific version) and didn't have the issue, I then updated to chrome 73 (as above), and the issue began to happen.

**Comment by nkbt** [comment] 2019-04-16 22:57
I've just checked on my working machine (macos), no issues as well.

>
